### ISSUE TITLE
Error when using newly added template

### ISSUE THREAD

**Issue by samcat116** [cooperpellaton/NachoMemes#138]
After adding the following template using `!memebot save`
```json
{
  "name": "they-dont-know",
  "image_url": "https://i.imgur.com/1DwKaAu.png",
  "textboxes": [
    {
      "left": 0.25,
      "right": 0.75,
      "top": 0.1,
      "bottom": 0.3,
      "font": "IMPACT",
      "max_font_size": 100,
      "color": "BLACK",
      "justify": "LEFT",
      "ind_size": false
    }
  ],
  "layout": "party_layout",
  "description": "I wish I was at home playing video games",
  "docs": "https://knowyourmeme.com/memes/i-wish-i-was-at-home-they-dont-know",
  "usage": 0
}
```
the bot gives an error stating:
> An error has occured
>function takes exactly 1 argument (3 given)

**Comment by ironchefpython** [comment]
User Error
**WONTFIX**

**Comment by samcat116** [comment]
Seems like it was an issue with that specific URL, as a different URL with the same image didn't cause this issue.

**Comment by coreysabia** [comment]
User error. 

**WONT FIX**

**Comment by ironchefpython** [comment]
WONTFIX
O
N
T
F
X

**Comment by coreysabia** [comment]
W O N T F I X
O N T F I X
N T F I X
T F I X
F I X
I X
X

**Comment by jswny** [comment]
![image](https://user-images.githubusercontent.com/3282078/124340350-8e9fc980-db82-11eb-8982-588e4ad3aa1c.jpeg)
