### ISSUE TITLE
Consolidate bot commands

### ISSUE THREAD

**Issue by ironchefpython** [cooperpellaton/NachoMemes#59]
Reduce the number of commands to reduce the chance of conflicts.

**Comment by ironchefpython** [comment]
I suggest the following:

`/meme` list memes

`/meme name*` list fuzzy matched memes

`/meme name` display meme info

`/meme name message` render and display a meme

`/memebot` list commands

`/memebot refresh` refresh meme templates

`/memebot set-admin-role roleid` set the admin role of for the guild

Etc.

**Comment by cooperpellaton** [comment]
Closed in #64. Need to open a new issue for grouping commands using `commands.Group()` @ironchefpython.
